<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE catalogo [
  <!ELEMENT catalogo (prenda+)>
  <!ELEMENT prenda (id, nombre, tipo, marca, precio, colores, materiales, temporada, tallas, instrucciones_cuidado, popularidad, imagen)>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT tipo (#PCDATA)>
  <!ELEMENT marca (#PCDATA)>
  <!ELEMENT precio (#PCDATA)>
  <!ELEMENT colores (color+)>
  <!ELEMENT color (#PCDATA)>
  <!ELEMENT materiales (material+)>
  <!ELEMENT material (#PCDATA)>
  <!ELEMENT temporada (#PCDATA)>
  <!ELEMENT tallas (talla+)>
  <!ELEMENT talla (#PCDATA)>
  <!ELEMENT instrucciones_cuidado (#PCDATA)>
  <!ELEMENT popularidad (#PCDATA)>
  <!ELEMENT imagen (#PCDATA)>
]>
<catalogo>
  <prenda>
    <id>002</id>
    <nombre>Vestido de verano</nombre>
    <tipo>Vestido</tipo>
    <marca>InnovarTech</marca>
    <precio>59.99</precio>
    <colores>
      <color>Rojo</color>
      <color>Azul</color>
    </colores>
    <materiales>
      <material>Algodón</material>
      <material>Lino</material>
    </materiales>
    <temporada>Verano<temporada>
    <tallas>
      <talla>S</talla>
      <talla>M</talla>
      <talla>L</talla>
      <talla>XL</talla>
    </tallas>
    <cuidado>Lavar a máquina a 30°C</cuidado>
    <popularidad>7.4</popularidad>
    <imagen>http://ejemplo.com/imagen/vestido_verano.jpg</imagen>
  </prenda>
</catalogo>